Exercise:

Load the cancer dataset and choose the best classification algorithm with the best hyperparameters.

1. Define X and y

2. To simplify, remove missing values

3. Split data to train and test

4. Use 5 fold cross validation and grid search on train data

5. Choose appropriate validation metric

6. Set grid parameters for each classification algorithm

7. Build the best models for each classification algorithm according to the best estimator (best hyperparameters) given by the grid search

8. Compare the performance of the algorithms with the best hyperparametrs on the test data according to confusion matrix, recall, precision, F1, and auc metrics

In [4]:
# load the dataset from Gdrive
from google.colab import drive
drive.mount('/gdrive/', force_remount=True)

import pandas as pd
df=pd.read_csv('/gdrive/MyDrive/CAD_AI/Supervised_Machine_Learning/data/breast_cancer_wisconsin.csv')
df

Mounted at /gdrive/

,Id,Cl.thickness,Cell.size,Cell.shape,Marg.adhesion,Epith.c.size,Bare.nuclei,Bl.cromatin,Normal.nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1.0,3,1,1,0
1,1002945,5,4,4,5,7,10.0,3,2,1,0
2,1015425,3,1,1,1,2,2.0,3,1,1,0
3,1016277,6,8,8,1,3,4.0,3,7,1,0
4,1017023,4,1,1,3,2,1.0,3,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2.0,1,1,1,0
695,841769,2,1,1,1,2,1.0,1,1,1,0
696,888820,5,10,10,3,7,3.0,8,10,2,1
697,897471,4,8,6,4,3,4.0,10,6,1,1
698,897471,4,8,8,5,4,5.0,10,4,1,1

In [6]:
# inspect data to identify feature (X) and target (y)

df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               699 non-null    int64
 1   Cl.thickness     699 non-null    int64
 2   Cell.size        699 non-null    int64
 3   Cell.shape       699 non-null    int64
 4   Marg.adhesion    699 non-null    int64
 5   Epith.c.size     699 non-null    int64
 6   Bare.nuclei      683 non-null    float64
 7   Bl.cromatin      699 non-null    int64
 8   Normal.nucleoli  699 non-null    int64
 9   Mitoses          699 non-null    int64
 10  Class            699 non-null    int64
dtypes: float64(1), int64(10)
memory usage: 60.2 KB

Id                  0
Cl.thickness        0
Cell.size           0
Cell.shape          0
Marg.adhesion       0
Epith.c.size        0
Bare.nuclei        16
Bl.cromatin         0
Normal.nucleoli     0
Mitoses             0
Class               0
dtype: int64

In [7]:
# The target variable is Class, where:
# 0 = Benign
# 1 = Malignant

X = df.drop(['Id','Class'], axis=1)
y = df['Class']

In [10]:
# remove missing data

df = df.dropna()

In [11]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 683 entries, 0 to 698
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               683 non-null    int64
 1   Cl.thickness     683 non-null    int64
 2   Cell.size        683 non-null    int64
 3   Cell.shape       683 non-null    int64
 4   Marg.adhesion    683 non-null    int64
 5   Epith.c.size     683 non-null    int64
 6   Bare.nuclei      683 non-null    float64
 7   Bl.cromatin      683 non-null    int64
 8   Normal.nucleoli  683 non-null    int64
 9   Mitoses          683 non-null    int64
 10  Class            683 non-null    int64
dtypes: float64(1), int64(10)
memory usage: 64.0 KB

Id                 0
Cl.thickness       0
Cell.size          0
Cell.shape         0
Marg.adhesion      0
Epith.c.size       0
Bare.nuclei        0
Bl.cromatin        0
Normal.nucleoli    0
Mitoses            0
Class              0
dtype: int64

In [18]:
# check features
X.head()

,Cl.thickness,Cell.size,Cell.shape,Marg.adhesion,Epith.c.size,Bare.nuclei,Bl.cromatin,Normal.nucleoli,Mitoses
0,5,1,1,1,2,1.0,3,1,1
1,5,4,4,5,7,10.0,3,2,1
2,3,1,1,1,2,2.0,3,1,1
3,6,8,8,1,3,4.0,3,7,1
4,4,1,1,3,2,1.0,3,1,1

In [19]:
# split data from training and testing
# test_size=0.20 --> 80% training, 20% testing
# random_state=42 --> reproducible results
# stratify=y --> maintain class distribution

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

In [20]:
# Scale the features, standardise numerical values

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
# logistic regression

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
lr_params = {
    'C':[0.01,0.1,1,10,100]
}
lr_grid = GridSearchCV(
    LogisticRegression(max_iter=1000),
    lr_params,
    cv=5,
    scoring='f1'
)

lr_grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000),
             param_grid={'C': [0.01, 0.1, 1, 10, 100]}, scoring='f1')

In [27]:
# lr best params

lr_grid.best_params_

{'C': 1}

In [24]:
# knn

from sklearn.neighbors import KNeighborsClassifier

knn_params = {
'n_neighbors':[3,5,7,9,11],
'weights':['uniform','distance']
}

knn_grid = GridSearchCV(
    KNeighborsClassifier(),
    knn_params,
    cv=5,
    scoring='f1'
)

knn_grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='f1')

In [28]:
# knn best params
knn_grid.best_params_

{'n_neighbors': 7, 'weights': 'uniform'}

In [25]:
# decision tree

from sklearn.tree import DecisionTreeClassifier

dt_params = {
    'max_depth':[3,5,7,10],
    'min_samples_split':[2,5,10]
}

dt_grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    dt_params,
    cv=5,
    scoring='f1'
)

dt_grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'max_depth': [3, 5, 7, 10],
                         'min_samples_split': [2, 5, 10]},
             scoring='f1')

In [29]:
# dt best params
dt_grid.best_params_

{'max_depth': 7, 'min_samples_split': 5}

In [26]:
# svm

from sklearn.svm import SVC

svm_params = {
    'C':[0.1,1,10],
    'kernel':['linear','rbf']
}

svm_grid = GridSearchCV(
    SVC(probability=True),
    svm_params,
    cv=5,
    scoring='f1'
)

svm_grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=SVC(probability=True),
             param_grid={'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf']},
             scoring='f1')

In [30]:
#svm best params
svm_grid.

{'C': 0.1, 'kernel': 'linear'}

In [31]:
# show all best hyperparameters

print("LR:", lr_grid.best_params_)
print("KNN:", knn_grid.best_params_)
print("DT:", dt_grid.best_params_)
print("SVM:", svm_grid.best_params_)

LR: {'C': 1}
KNN: {'n_neighbors': 7, 'weights': 'uniform'}
DT: {'max_depth': 7, 'min_samples_split': 5}
SVM: {'C': 0.1, 'kernel': 'linear'}

In [34]:
# retrieve best models from grid search

best_lr = lr_grid.best_estimator_
best_knn = knn_grid.best_estimator_
best_dt = dt_grid.best_estimator_
best_svm = svm_grid.best_estimator_

In [33]:
# define test set

from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

In [38]:
#evaluate each model
def evaluate_model(model, X_test, y_test):

    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]
    print("Confusion Matrix")
    print(confusion_matrix(y_test,y_pred))
    print("Precision:", precision_score(y_test,y_pred))
    print("Recall:", recall_score(y_test,y_pred))
    print("F1:", f1_score(y_test,y_pred))
    print("AUC:", roc_auc_score(y_test,y_prob))

print("Logistic Regression")
evaluate_model(best_lr,X_test_scaled,y_test)

print("\nKNN")
evaluate_model(best_knn,X_test_scaled,y_test)

print("\nDecision Tree")
evaluate_model(best_dt,X_test_scaled,y_test)

print("\nSVM")
evaluate_model(best_svm,X_test_scaled,y_test)

Logistic Regression
Confusion Matrix
[[85  4]
 [ 1 47]]
Precision: 0.9215686274509803
Recall: 0.9791666666666666
F1: 0.9494949494949495
AUC: 0.9918071161048689

KNN
Confusion Matrix
[[85  4]
 [ 2 46]]
Precision: 0.92
Recall: 0.9583333333333334
F1: 0.9387755102040817
AUC: 0.9827949438202247

Decision Tree
Confusion Matrix
[[85  4]
 [ 2 46]]
Precision: 0.92
Recall: 0.9583333333333334
F1: 0.9387755102040817
AUC: 0.9557584269662922

SVM
Confusion Matrix
[[85  4]
 [ 2 46]]
Precision: 0.92
Recall: 0.9583333333333334
F1: 0.9387755102040817
AUC: 0.9932116104868913

In [37]:
# identify best algorithm

results = pd.DataFrame({
    'Model':['Logistic Regression','KNN','Decision Tree','SVM'],
    'Best_CV_F1':[
        lr_grid.best_score_,
        knn_grid.best_score_,
        dt_grid.best_score_,
        svm_grid.best_score_
    ]
})

results.sort_values(
    by='Best_CV_F1',
    ascending=False
)

                 Model  Best_CV_F1
1                  KNN    0.968541
0  Logistic Regression    0.957735
3                  SVM    0.955691
2        Decision Tree    0.939519